### ISSUE TITLE
启用插件后，使用“#群友表情”指令时控制台报错

### ISSUE THREAD

**Issue by QSlotus** [cssxsh/meme-helper#10]
如题，但是不影响整个框架的使用（已安装Mirai Hibernate Plugin

    2023-03-29 16:37:53 W/meme-helper: MemeHelper Handle Exception
    java.lang.reflect.InvocationTargetException
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	    at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	    at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	    at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	    at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:56)
	    at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:80)
	    at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callFunction(JvmMethodListenersInternal.kt:1)
	    at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invokeSuspend(JvmMethodListenersInternal.kt:110)
	    at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invoke(JvmMethodListenersInternal.kt)
	    at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invoke(JvmMethodListenersInternal.kt)
	    at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:480)
	    at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	    at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	    at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
	    at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	    at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
	    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	    at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
	    at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:120)
	    at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:68)
	    at net.mamoe.mirai.internal.event.EventListeners$callListeners$1.invokeSuspend(EventListeners.kt)
	    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	    at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Caused by: java.util.NoSuchElementException: Cannot get random in empty range: 0..-1
	    at kotlin.ranges.RangesKt___RangesKt.random(_Ranges.kt:193)
	    at mirai-hibernate-plugin-2.7.1.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateUtilsKt.random$lambda$6(MiraiHibernateUtils.kt:119)
	    at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.SessionFactory.fromSession(SessionFactory.java:197)
	    at mirai-hibernate-plugin-2.7.1.mirai2.jar//xyz.cssxsh.mirai.hibernate.MiraiHibernateUtilsKt.random(MiraiHibernateUtils.kt:108)
	    at meme-helper-1.2.0.mirai2.jar//xyz.cssxsh.mirai.meme.impl.MemeRecord.replier(MemeRecord.kt:68)
	    at meme-helper-1.2.0.mirai2.jar//xyz.cssxsh.mirai.meme.MemeHelper.handle(MemeHelper.kt:28)
	    ... 35 more

**Comment by cssxsh** [comment]
`#群友表情` 需要先收集到表情包才能用
